# Docker Compose pour SonicDiscover V2 - Production avec Coolify
version: '3.8'

services:
  # Application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: sonicdiscover-app
    restart: unless-stopped
    environment:
      # Base de données (gérée par Coolify)
      DATABASE_URL: ${DATABASE_URL}
      
      # Application
      NODE_ENV: production
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      JWT_SECRET: ${JWT_SECRET}
      
      # APIs externes
      GROQ_API_KEY: ${GROQ_API_KEY}
      
      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    volumes:
      # Volume pour les uploads et fichiers statiques persistants
      - app_uploads:/app/public/uploads
      - app_music:/app/public/music

# Volumes persistants
volumes:
  app_uploads:
    driver: local
  app_music:
    driver: local
